#!/bin/sh

# Autostart
for i in polybar sxhkd unclutter numlockx
do
    killall $i
done

#autorandr --change
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
[ "$(xrandr | grep 'DP1-3')" ] && xrandr --output eDP1 --off --output DP1-3 --primary --mode 2560x1440

# applications/commands on start
setxkbmap -option caps:escape
dunst &
xrdb "$HOME"/.Xresources &
unclutter &
numlockx &
pgrep bspswallow || bspswallow &
sxhkd &
davmail &
setbg &
polybar default &

# Unused monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Colors
bspc config active_border_color "#128aed"
bspc config focused_border_color "#7d38d8"
bspc config presel_feedback_color "#000000"

# Monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Tiling
#bspc config automatic_scheme spiral
#bspc config automatic_scheme alternate
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

# Pointer configurations
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# Window rules
bspc rule -a Lxappearance state=floating
#bspc rule -a Nextcloud state=tiled
#Add Nextcloud account
bspc rule -a Zathura state=tiled
#bspc rule -a Slack:slack -o node=@^1:^10:/2
bspc rule -a Ferdium:ferdium -o node=@^1:^10:/1

